minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@maxnth/gestalt'

allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  esbuild: true
  maplibre-gl: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
