services:
  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    volumes:
      - ./:/workspace:Z
      - /workspace/docs/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs.rule=Host(`docs.localhost`)"
      - "traefik.http.routers.docs.entrypoints=web"
      - "traefik.http.services.docs.loadbalancer.server.port=3000"
