services:
  docs:
    build:
      context: docs
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "${LAREX_BIND_IP:-127.0.0.1}:${LAREX_DOCS_PORT:-3001}:3000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
