services:
  app:
    environment:
      KEYCLOAK_ADMIN_SERVER_URL: ${KEYCLOAK_ADMIN_SERVER_URL:-https://${KEYCLOAK_PUBLIC_HOST:-auth.example.org}}
      KEYCLOAK_ADMIN_REALM: ${KEYCLOAK_REALM:-larex-prod}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:-https://${KEYCLOAK_PUBLIC_HOST:-auth.example.org}/realms/${KEYCLOAK_REALM:-larex-prod}}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:-https://${KEYCLOAK_PUBLIC_HOST:-auth.example.org}/realms/${KEYCLOAK_REALM:-larex-prod}/protocol/openid-connect/certs}

  frontend:
    environment:
      NUXT_OAUTH_KEYCLOAK_SERVER_URL: ${NUXT_OAUTH_KEYCLOAK_SERVER_URL:-https://${KEYCLOAK_PUBLIC_HOST:-auth.example.org}}
      NUXT_OAUTH_KEYCLOAK_SERVER_URL_INTERNAL: ${NUXT_OAUTH_KEYCLOAK_SERVER_URL_INTERNAL:-https://${KEYCLOAK_PUBLIC_HOST:-auth.example.org}}
      NUXT_OAUTH_KEYCLOAK_REALM: ${KEYCLOAK_REALM:-larex-prod}
