/**
 * PAGE XML enum values extracted from frontend/pagecontent.xsd
 */

export const LANGUAGE_SIMPLE_TYPE_VALUES = [
  'Abkhaz',
  'Afar',
  'Afrikaans',
  'Akan',
  'Albanian',
  'Amharic',
  'Arabic',
  'Aragonese',
  'Armenian',
  'Assamese',
  'Avaric',
  'Avestan',
  'Aymara',
  'Azerbaijani',
  'Bambara',
  'Bashkir',
  'Basque',
  'Belarusian',
  'Bengali',
  'Bihari',
  'Bislama',
  'Bosnian',
  'Breton',
  'Bulgarian',
  'Burmese',
  'Cambodian',
  'Cantonese',
  'Catalan',
  'Chamorro',
  'Chechen',
  'Chichewa',
  'Chinese',
  'Chuvash',
  'Cornish',
  'Corsican',
  'Cree',
  'Croatian',
  'Czech',
  'Danish',
  'Divehi',
  'Dutch',
  'Dzongkha',
  'English',
  'Esperanto',
  'Estonian',
  'Ewe',
  'Faroese',
  'Fijian',
  'Finnish',
  'French',
  'Fula',
  'Gaelic',
  'Galician',
  'Ganda',
  'Georgian',
  'German',
  'Greek',
  'Guaraní',
  'Gujarati',
  'Haitian',
  'Hausa',
  'Hebrew',
  'Herero',
  'Hindi',
  'Hiri Motu',
  'Hungarian',
  'Icelandic',
  'Ido',
  'Igbo',
  'Indonesian',
  'Interlingua',
  'Interlingue',
  'Inuktitut',
  'Inupiaq',
  'Irish',
  'Italian',
  'Japanese',
  'Javanese',
  'Kalaallisut',
  'Kannada',
  'Kanuri',
  'Kashmiri',
  'Kazakh',
  'Khmer',
  'Kikuyu',
  'Kinyarwanda',
  'Kirundi',
  'Komi',
  'Kongo',
  'Korean',
  'Kurdish',
  'Kwanyama',
  'Kyrgyz',
  'Lao',
  'Latin',
  'Latvian',
  'Limburgish',
  'Lingala',
  'Lithuanian',
  'Luba-Katanga',
  'Luxembourgish',
  'Macedonian',
  'Malagasy',
  'Malay',
  'Malayalam',
  'Maltese',
  'Manx',
  'Māori',
  'Marathi',
  'Marshallese',
  'Mongolian',
  'Nauru',
  'Navajo',
  'Ndonga',
  'Nepali',
  'North Ndebele',
  'Northern Sami',
  'Norwegian',
  'Norwegian Bokmål',
  'Norwegian Nynorsk',
  'Nuosu',
  'Occitan',
  'Ojibwe',
  'Old Church Slavonic',
  'Oriya',
  'Oromo',
  'Ossetian',
  'Pāli',
  'Panjabi',
  'Pashto',
  'Persian',
  'Polish',
  'Portuguese',
  'Punjabi',
  'Quechua',
  'Romanian',
  'Romansh',
  'Russian',
  'Samoan',
  'Sango',
  'Sanskrit',
  'Sardinian',
  'Serbian',
  'Shona',
  'Sindhi',
  'Sinhala',
  'Slovak',
  'Slovene',
  'Somali',
  'South Ndebele',
  'Southern Sotho',
  'Spanish',
  'Sundanese',
  'Swahili',
  'Swati',
  'Swedish',
  'Tagalog',
  'Tahitian',
  'Tajik',
  'Tamil',
  'Tatar',
  'Telugu',
  'Thai',
  'Tibetan',
  'Tigrinya',
  'Tonga',
  'Tsonga',
  'Tswana',
  'Turkish',
  'Turkmen',
  'Twi',
  'Uighur',
  'Ukrainian',
  'Urdu',
  'Uzbek',
  'Venda',
  'Vietnamese',
  'Volapük',
  'Walloon',
  'Welsh',
  'Western Frisian',
  'Wolof',
  'Xhosa',
  'Yiddish',
  'Yoruba',
  'Zhuang',
  'Zulu',
  'other'
] as const

export const SCRIPT_SIMPLE_TYPE_VALUES = [
  'Adlm - Adlam',
  'Afak - Afaka',
  'Aghb - Caucasian Albanian',
  'Ahom - Ahom, Tai Ahom',
  'Arab - Arabic',
  'Aran - Arabic (Nastaliq variant)',
  'Armi - Imperial Aramaic',
  'Armn - Armenian',
  'Avst - Avestan',
  'Bali - Balinese',
  'Bamu - Bamum',
  'Bass - Bassa Vah',
  'Batk - Batak',
  'Beng - Bengali',
  'Bhks - Bhaiksuki',
  'Blis - Blissymbols',
  'Bopo - Bopomofo',
  'Brah - Brahmi',
  'Brai - Braille',
  'Bugi - Buginese',
  'Buhd - Buhid',
  'Cakm - Chakma',
  'Cans - Unified Canadian Aboriginal Syllabics',
  'Cari - Carian',
  'Cham - Cham',
  'Cher - Cherokee',
  'Cirt - Cirth',
  'Copt - Coptic',
  'Cprt - Cypriot',
  'Cyrl - Cyrillic',
  'Cyrs - Cyrillic (Old Church Slavonic variant)',
  'Deva - Devanagari (Nagari)',
  'Dsrt - Deseret (Mormon)',
  'Dupl - Duployan shorthand, Duployan stenography',
  'Egyd - Egyptian demotic',
  'Egyh - Egyptian hieratic',
  'Egyp - Egyptian hieroglyphs',
  'Elba - Elbasan',
  'Ethi - Ethiopic',
  'Geok - Khutsuri (Asomtavruli and Nuskhuri)',
  'Geor - Georgian (Mkhedruli)',
  'Glag - Glagolitic',
  'Goth - Gothic',
  'Gran - Grantha',
  'Grek - Greek',
  'Gujr - Gujarati',
  'Guru - Gurmukhi',
  'Hanb - Han with Bopomofo',
  'Hang - Hangul',
  'Hani - Han (Hanzi, Kanji, Hanja)',
  'Hano - Hanunoo (Hanunóo)',
  'Hans - Han (Simplified variant)',
  'Hant - Han (Traditional variant)',
  'Hatr - Hatran',
  'Hebr - Hebrew',
  'Hira - Hiragana',
  'Hluw - Anatolian Hieroglyphs',
  'Hmng - Pahawh Hmong',
  'Hrkt - Japanese syllabaries',
  'Hung - Old Hungarian (Hungarian Runic)',
  'Inds - Indus (Harappan)',
  'Ital - Old Italic (Etruscan, Oscan etc.)',
  'Jamo - Jamo',
  'Java - Javanese',
  'Jpan - Japanese',
  'Jurc - Jurchen',
  'Kali - Kayah Li',
  'Kana - Katakana',
  'Khar - Kharoshthi',
  'Khmr - Khmer',
  'Khoj - Khojki',
  'Kitl - Khitan large script',
  'Kits - Khitan small script',
  'Knda - Kannada',
  'Kore - Korean (alias for Hangul + Han)',
  'Kpel - Kpelle',
  'Kthi - Kaithi',
  'Lana - Tai Tham (Lanna)',
  'Laoo - Lao',
  'Latf - Latin (Fraktur variant)',
  'Latg - Latin (Gaelic variant)',
  'Latn - Latin',
  'Leke - Leke',
  'Lepc - Lepcha (Róng)',
  'Limb - Limbu',
  'Lina - Linear A',
  'Linb - Linear B',
  'Lisu - Lisu (Fraser)',
  'Loma - Loma',
  'Lyci - Lycian',
  'Lydi - Lydian',
  'Mahj - Mahajani',
  'Mand - Mandaic, Mandaean',
  'Mani - Manichaean',
  'Marc - Marchen',
  'Maya - Mayan hieroglyphs',
  'Mend - Mende Kikakui',
  'Merc - Meroitic Cursive',
  'Mero - Meroitic Hieroglyphs',
  'Mlym - Malayalam',
  'Modi - Modi, Moḍī',
  'Mong - Mongolian',
  'Moon - Moon (Moon code, Moon script, Moon type)',
  'Mroo - Mro, Mru',
  'Mtei - Meitei Mayek (Meithei, Meetei)',
  'Mult - Multani',
  'Mymr - Myanmar (Burmese)',
  'Narb - Old North Arabian (Ancient North Arabian)',
  'Nbat - Nabataean',
  'Newa - Newa, Newar, Newari',
  'Nkgb - Nakhi Geba',
  'Nkoo - N’Ko',
  'Nshu - Nüshu',
  'Ogam - Ogham',
  'Olck - Ol Chiki (Ol Cemet’, Ol, Santali)',
  'Orkh - Old Turkic, Orkhon Runic',
  'Orya - Oriya',
  'Osge - Osage',
  'Osma - Osmanya',
  'Palm - Palmyrene',
  'Pauc - Pau Cin Hau',
  'Perm - Old Permic',
  'Phag - Phags-pa',
  'Phli - Inscriptional Pahlavi',
  'Phlp - Psalter Pahlavi',
  'Phlv - Book Pahlavi',
  'Phnx - Phoenician',
  'Piqd - Klingon (KLI pIqaD)',
  'Plrd - Miao (Pollard)',
  'Prti - Inscriptional Parthian',
  'Rjng - Rejang (Redjang, Kaganga)',
  'Roro - Rongorongo',
  'Runr - Runic',
  'Samr - Samaritan',
  'Sara - Sarati',
  'Sarb - Old South Arabian',
  'Saur - Saurashtra',
  'Sgnw - SignWriting',
  'Shaw - Shavian (Shaw)',
  'Shrd - Sharada, Śāradā',
  'Sidd - Siddham',
  'Sind - Khudawadi, Sindhi',
  'Sinh - Sinhala',
  'Sora - Sora Sompeng',
  'Sund - Sundanese',
  'Sylo - Syloti Nagri',
  'Syrc - Syriac',
  'Syre - Syriac (Estrangelo variant)',
  'Syrj - Syriac (Western variant)',
  'Syrn - Syriac (Eastern variant)',
  'Tagb - Tagbanwa',
  'Takr - Takri',
  'Tale - Tai Le',
  'Talu - New Tai Lue',
  'Taml - Tamil',
  'Tang - Tangut',
  'Tavt - Tai Viet',
  'Telu - Telugu',
  'Teng - Tengwar',
  'Tfng - Tifinagh (Berber)',
  'Tglg - Tagalog (Baybayin, Alibata)',
  'Thaa - Thaana',
  'Thai - Thai',
  'Tibt - Tibetan',
  'Tirh - Tirhuta',
  'Ugar - Ugaritic',
  'Vaii - Vai',
  'Visp - Visible Speech',
  'Wara - Warang Citi (Varang Kshiti)',
  'Wole - Woleai',
  'Xpeo - Old Persian',
  'Xsux - Cuneiform, Sumero-Akkadian',
  'Yiii - Yi',
  'Zinh - Code for inherited script',
  'Zmth - Mathematical notation',
  'Zsye - Symbols (Emoji variant)',
  'Zsym - Symbols',
  'Zxxx - Code for unwritten documents',
  'Zyyy - Code for undetermined script',
  'Zzzz - Code for uncoded script',
  'other'
] as const

export type LanguageSimpleTypeValue = (typeof LANGUAGE_SIMPLE_TYPE_VALUES)[number]
export type ScriptSimpleTypeValue = (typeof SCRIPT_SIMPLE_TYPE_VALUES)[number]
