package de.uniwue.zpd.dachs.larex.backend.exception;

public enum AdminUserErrorCode {
    ADMIN_USER_DUPLICATE_USERNAME,
    ADMIN_USER_DUPLICATE_EMAIL,
    ADMIN_USER_INVALID_USERNAME,
    ADMIN_USER_NOT_FOUND,
    ADMIN_USER_SERVICE_ACCOUNT_FORBIDDEN,
    ADMIN_USER_SELF_DISABLE_FORBIDDEN,
    ADMIN_USER_ALREADY_ENABLED,
    ADMIN_USER_ALREADY_DISABLED,
    ADMIN_USER_RESEND_NOT_ALLOWED,
    ADMIN_USER_PROVISIONING_DISABLED,
    ADMIN_USER_EXTERNALLY_MANAGED,
    ADMIN_USER_SETUP_EMAIL_FAILED,
    ADMIN_USER_KEYCLOAK_OPERATION_FAILED
}
